---
dependency:
  name: galaxy
driver:
  name: ec2
  options:
    ansible_connection_options:
      ansible_user: ec2-user
lint:
  name: yamllint
platforms:
  - name: instance
    image: ami-01a834fd83ae239ff
    instance_type: t2.micro
    vpc_subnet_id: subnet-0119f731caf79aa52
    group_id: sg-0254e2e1b0076afaf
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  connection_options:
    ansible_user: ec2-user
  playbooks:
    converge: ../resources/playbooks/converge.yml
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
